### PR TITLE
make passing signals on to spawned cmd optional

### PR DESCRIPTION
**Pull request by dropwhile**
When upstart restarts a managed process, it sends a TERM to every process in the process group (effectively a `kill -SIGTERM -${child-pid}`. The dash there is key.

This breaks an app I have that attempts to do a graceful shutdown using [stretchr/graceful](https://github.com/stretchr/graceful/), because it has the effect of sending two term signals to the child -- one directly and one via logexec. Depending on timing, if the signals arrive far enough apart, the app crashes pretty hard.

Would you accept a patch that made passing the signals on optional, but with a default of true?
`-signals=true` or something similar?

### CODE REVIEW

**Comment by dustin** [comment]
Sure, that should work.  Maybe -ignoresig or something.

**Comment by dropwhile** [comment]
@dustin attached pull req to this gh issue. Thinking about it after the fact, I probably should have just made a separate pull req -- apologies about that.

**Comment by dustin** [comment]
Nah, I don't really use the github pull request thing.  I usually just `git am` stuff, as I did here.  Thanks!

**Comment by dropwhile** [comment]
Groovy. Thanks!

**Pull request closed without merging**
